### ISSUE TITLE
SmartDashboard Not Found

### ISSUE THREAD

**Issue by BryanZChen** [FRC-Team-955/Team-955-Infinite-Recharge-2020#3]
Can not find script file
"C:\Users\Public\wpilib\2020\tools\SmartDashboard.vbs"

**Comment by jp-li** [comment]
[FIX] This issue is caused by not having the correct files installed on your driver station. Follow [this](https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html) guide to install the necessary files. 
*Side note: you can uncheck all boxes except for "Java JRE/JDK and Tools and Utilities" for a faster install if you are not planning to use code on the laptop.
